<?php
ini_set("include_path", "..".PATH_SEPARATOR.ini_get("include_path"));
require_once 'PHPUnit/Framework.php';

require_once 'Templum.php';

/**
 * Test class for Templum_Exception.
 * Generated by PHPUnit on 2009-08-28 at 11:16:35.
 */
class Templum_ExceptionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Templum_Exception
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Templum_Exception;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }
}
?>
